# Generated by Django 5.2.9 on 2025-12-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recipe_preparation_time_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='day',
            field=models.DateField(help_text='Date du repas'),
        ),
    ]
