# Generated by Django 6.0.2 on 2026-02-07 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_alter_recipe_options_recipe_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Carbohydrates in grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fats in grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Protein in grams', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Order of this step')),
                ('title', models.CharField(blank=True, help_text='Optional step title', max_length=100)),
                ('instruction', models.TextField(help_text='Detailed instruction for this step')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Time needed for this step', null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional step image', null=True, upload_to='steps/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_steps', to='home.recipe')),
            ],
            options={
                'ordering': ['recipe', 'step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recipe', 'user')},
            },
        ),
    ]
